name: Pull Request

on:
  pull_request:
    types: [opened, ready_for_review]
    branches-ignore:
      - "main"
      - "release-**"

jobs:
  pull_request:
    if: ${{ !github.event.pull_request.draft }}
    name: Create PR alarm
    runs-on: ubuntu-latest
    steps:
      - name: Send comment alarm message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            ìƒˆë¡œìš´ PRì´ ìƒì„±ë˜ì—ˆìŠµë‹ˆë‹¤! ğŸ«

            ğŸ“° PR ì œëª©: ${{ github.event.pull_request.title }}
            ğŸ‘¤ PR ì‘ì„±ì: ${{ github.event.pull_request.user.login }}
            ğŸ«‚ ë¦¬ë·°ì–´: ${{ github.event.pull_request.requested_reviewers[0].login }}

            ë‹¤ìŒ [ë§í¬](${{ github.event.pull_request.html_url }})ë¥¼ í™•ì¸í•´ì£¼ì„¸ìš”!
